### ISSUE TITLE
Update to Latest Release

### ISSUE THREAD

**Issue by sameersharma2006** [sameersharma2006/curtail#2]
With the latest release of curtail, the snap won't open with the following message :
```
Traceback (most recent call last):
  File "/snap/curtail/101/usr/bin/curtail", line 44, in <module>
    from curtail import main
  File "/snap/curtail/current/usr/share/curtail/curtail/main.py", line 26, in <module>
    from .window import CurtailWindow
  File "/snap/curtail/current/usr/share/curtail/curtail/window.py", line 23, in <module>
    from .preferences import CurtailPrefsDialog
  File "/snap/curtail/current/usr/share/curtail/curtail/preferences.py", line 26, in <module>
    class CurtailPrefsDialog(Adw.PreferencesDialog):
  File "/snap/curtail/101/gnome-platform/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'PreferencesDialog'. Did you mean: 'PreferencesWindow'?
```

This is due to the fact that the snap is based on core22 & uses gnome-42-2204 SDK for adwaita etc.
But being from core22, they may not contain the latest libs and hence halts the app from starting due to lack of latest libs 

**Solution**
* Upgrade to core24 & gnome-46-2404 (Not Available Yet ! :disappointed:  )
*  Patch up the snap to revert this commit https://github.com/Huluti/Curtail/commit/37aecb38d5b6bbc593bb2c47f48840d881b93038 (Not feasible ideally)

Hence, i believe best bet will be to wait for core24 & gnome-46-2404 although if they get delayed further i will try patching .

**Comment by sameersharma2006** [comment]
After few fixes in gnome-46-2404, i have got latest versions of curtail work atop core24 & gnome-46-2404(edge channel).
Once the fixes of the gnome stack lands in its stable, new version will be published.
